### ISSUE TITLE
Add a command to create test data

### ISSUE THREAD

**Issue by oliverklee** [TYPO3BestPractices/tea#1120]
## Goal
I as a user would like to create test records.

## Acceptance Criteria

- [ ] a command controller is added for creating the test records in a existing sysfolder. Pid of this folder as option
- [ ] the command controller has an option to delete existing records in this sysfolder.

## Additional Information
For manual testing, it would be helpful to have a (Symfony?) command to create some test records.

This could also server as an example for creating commands.

The script should also throw away old test data.

**Comment by kanow** [comment]
my idea:

- create a command controller to creating new data in an existing sysfolder. pid must be set as argument
- add second option to delete existing data in that pid
- maybe later extend the command or use another to create that syfolder before. But maybe that's not useful. I'm not sure.

**Comment by oliverklee** [comment]
Sounds generally good to me.

Also, I think we can always delete existing data. This is only for setting up test data quickly and not for usage on a production site.
