### ISSUE TITLE
Add the plugins to the newContentElement Wizard

### ISSUE THREAD

**Issue by linawolf** [TYPO3BestPractices/tea#825]
## Goal
As a developer I want to add the plugin to the newContentElement Wizard
## Acceptance Criteria

- [ ] the plugin is added to the Wizard

## Additional Information

I was considering to switch the example https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/Extbase/Reference/FrontendPlugins.html to the tea extension.

However I noted that there is not example for a newContentElement Wizard so I refrained from doing that for now.

For now I only copy the comments you have in the ext_localconf for `ExtensionUtility::configurePlugin` as they are really helpful, thanks for that!

**Comment by linxpinx** [comment]
@oliverklee @DanielSiepmann @lukaszuznanski is this ticket useful?

**Comment by oliverklee** [comment]
Yes, this still would be nice to have as an example (and to improve usability).

**Comment by linawolf** [comment]
With TYPO3 13 it is actually not needed anymore, see https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.0/Feature-102834-Auto-registrationOfNewContentElementWizardViaTCA.html#feature-102834-auto-registration-of-new-content-element-wizard-via-tca
